runtime: python38

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static
  
- url: /image/pokemon_PNG78.png
  static_files: pokemon_PNG78.png
  upload: pokemon_PNG78.png
  
- url: /image
  static_dir: image

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

